version: "2"
services:
  web:
    container_name: "web"
    restart: "always"
    depends_on:
      nginx:
        condition: "service_started"
      redis:
        condition: "service_started"
    volumes:
      - "/code:/project"
